# Generated by Django 3.0.2 on 2020-01-30 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='ingredients',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
