# Generated by Django 3.0.3 on 2020-03-02 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_author_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='favorites',
        ),
        migrations.AddField(
            model_name='author',
            name='favorites',
            field=models.ManyToManyField(related_name='favorites', to='recipe.Recipes'),
        ),
    ]
